version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME="admin"
      - MONGO_INITDB_ROOT_PASSWORD="admin786"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
    environment:
      SERVER_ERROR_INCLUDE_BINDING_ERRORS: "always"
      SERVER_ERROR_INCLUDE_MESSAGE: "always"
      SPRING_APPLICATION_JSON: '{"spring.data.mongodb.uri" : "mongodb://admin:admin786@mongodb:27017/notes"}'
